blogs/urls.py
from django.urls import path, include
from . import views

app_name = 'blogs'

urlpatterns = [
    path('', views.blogView, name='blogUrl'),
    path('postform', views.postFormView, name="postform"),
    path('<slug:slug>', views.fullBlogView, name='fullBlogUrl'),

]

events/urls.py
from django.urls import path, include
from . import views

app_name = 'events'

urlpatterns = [
    path('', views.eventView, name='eventUrl'),

]

feeds/urls.py
from django.urls import path, include
from . import views

app_name = 'feeds'

urlpatterns = [
    path('', views.home, name='home'),
    path('postform', views.postform, name="postform")
]


genz/urls.py
from django.contrib import admin
from django.urls import path, include
from . import settings
# from django.conf import settings.DEBUG
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('feeds.urls')),
    path('blogs/', include('blogs.urls')),
    path('events/', include('events.urls')),
    path('profile/', include('profiles.urls')),
]

if settings.DEBUG:
    print(settings.MEDIA_URL)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

profiles/urls.py
from django.urls import path
from . import views

app_name = 'profiles'

urlpatterns = [
    path('login', views.login, name='login'),
    path('register', views.register, name='register'),
    path('logout', views.logout, name='logout')
]

blogs/models.py
from django.db import models
from django.contrib.auth.models import User
from django.template.defaultfilters import slugify
from datetime import datetime

# Create your models here.
class Blog(models.Model):
    heading = models.CharField(max_length=200)
    textContent = models.TextField()
    blogSlug = models.SlugField(unique=True)
    imageContent = models.ImageField(upload_to='post', null=True)
    postedBy = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    postedOn = models.DateTimeField(default=datetime.now(), blank=True)

    def save(self, *args, **kwargs):  # new
        if not self.blogSlug:
            self.blogSlug = slugify(self.heading)
        return super().save(*args, **kwargs)

events/models.py
from django.db import models

# Create your models here.

feeds/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import datetime

# Create your models here.
class post(models.Model):
    textContent = models.TextField()
    imageContent = models.ImageField(upload_to='post', null=True)
    postedBy = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    postedOn = models.DateTimeField(default=datetime.now(), blank=True)

    class Meta:
        ordering = ['-postedOn']

profiles/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class profiles(models.Model):
    user = models.ForeignKey(User, on_delete = models.CASCADE)
    profileImage = models.ImageField(upload_to='profile', default='profile/default.jpeg')

blogs/forms.py
from django import forms

class postform(forms.Form):
    heading = forms.CharField()
    image = forms.ImageField(required=False)
    text = forms.CharField(widget=forms.Textarea(attrs={'class':'text', 'rows':'2','cols':'60', 'placeholder':'Write here ...'}))
    

feeds/forms.py
from django import forms

class postform(forms.Form):
    text = forms.CharField(
        widget=forms.Textarea(attrs=
                {'class':'text', 
                'rows':'2',
                'cols':'60', 
                'placeholder':'Write here ...',
                'name': 'text'}))
    image = forms.ImageField(required=False,)

blogs/views.py
from django.shortcuts import render, redirect
from . import forms
from . import models

# Create your views here.
def blogView(request):
    context = dict()
    blogs = models.Blog.objects.all()
    context['blogs'] = blogs
    print(blogs)
    return render(request, 'blog.html', context)

def fullBlogView(request, slug):
    context = {}
    blogs = models.Blog.objects.get(blogSlug=slug)
    context['blog'] = blogs
    
    return render(request, 'fullBlog.html', context)

def postFormView(request):
    context = {}
    user = request.user
    if request.method == "POST":
        form = forms.postform(request.POST, request.FILES)
        if form.is_valid():
            print(form.cleaned_data)
            heading = form.cleaned_data.get('heading')
            textContent = form.cleaned_data.get('text')
            imageContent = form.cleaned_data.get('image')
            obj = models.Blog.objects.create(heading=heading,
                                            textContent = textContent, 
                                             postedBy = user,
                                             imageContent = imageContent)
            obj.save()
            return redirect('feeds:home')
    context['form'] = forms.postform()
    return render(request, 'postform.html', context)

events/views.py
from django.shortcuts import render

# Create your views here.
def eventView(request):
    return render(request, 'events.html')

feeds/views.py
from django.shortcuts import render, redirect
from . import models
from profiles import models as profilemodels
from . import forms


# Create your views here.

def home(request):
    userId = request.user.id
    posts = models.post.objects.all()
    profiles = profilemodels.profiles.objects.all()
    context = {'posts': posts, 'profiles':profiles}
    return render(request, 'feeds.html', context)

def postform(request):
    context = {}
    user = request.user
    if request.method == "POST":
        form = forms.postform(request.POST, request.FILES)
        if form.is_valid():
            textContent = form.cleaned_data.get('text')
            imageContent = form.cleaned_data.get('image')
            obj = models.post.objects.create(textContent = textContent, 
                                             postedBy = user,
                                             imageContent = imageContent)
            obj.save()
            return redirect('feeds:home')
    context['form'] = forms.postform()
    return render(request, 'postform.html', context)


profiles/views.py
from django.shortcuts import render, redirect
from django.contrib import auth
from django.contrib.auth.models import User 
from django.contrib import messages
from . import models

# Create your views here.

def register(request):
        
    if request.method == 'POST':
        username = request.POST['username']
        email = request.POST['email']
        password = request.POST['password']
        password2 = request.POST['password2']

        if(password == password2):
            if User.objects.filter(email=email).exists():
                messages.info(request, 'EMAIL ALREADY EXIST!!!')
                return redirect('profiles:register')    
            elif User.objects.filter(username=username).exists():
                messages.info(request, 'USERNAME ALREADY EXIST!!!')
                return redirect('profiles:register')
            else:
                user = User.objects.create_user(username=username,email=email,password=password)
                user.save()
                profile = models.profiles(user=user)
                profile.save()
                return redirect('profiles:login')
        else:
            messages.info(request, 'INVALID PASSWORD!!!')
            return redirect('profiles:register')   
    else:     
        return render(request, 'register.html')
    
def login(request):
    if(request.method == "POST"):
        
        username=request.POST['username']
        password=request.POST['password']

        user=auth.authenticate(username=username,password=password)

        if user:
            auth.login(request,user)
            return redirect("feeds:home")
        else:
            messages.info(request, 'INVALID CREDENTIALS!!')
            return redirect('profiles:login')


    else:    
        return render(request, 'login.html')
    
def logout(request):
    auth.logout(request)
    return redirect("/")

templates/addcontent.html
<style>
    .addpost {
    position: fixed;
    bottom: 12%;
    right: 3%;
    background: linear-gradient(rgb(250, 29, 29), var(--major-blue-color));
    opacity: .7;
    border-radius: .4rem;
    height: 8%;
    aspect-ratio: 1/1;
    display: flex;
    justify-content: center;
    align-items: center;
}
.fa-plus {
    color: white;
}
</style>

<div class="addpost">
    <i class="fa-solid fa-plus fa-2xl"></i>
</div>

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
    {% block head %}
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        {% block title %}<title>cfc fans page</title>{% endblock %}
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Outfit:wght@400;700&family=Roboto:wght@400;700&family=Teko:wght@400;700&display=swap" rel="stylesheet">
        <link rel="stylesheet" href='{% static "base.css" %}'>
        <style>

            #chatbot{
                position: fixed;
                bottom: 20px;
                right: 100px;
                cursor: pointer;
            }
        </style>
        {% block extraStyle %}{% endblock %}
        {% block extraLink %}{% endblock %}
        <script 
        src="https://kit.fontawesome.com/81346837db.js" crossorigin="anonymous">
        </script>
    </head>
    {% endblock %}
    <body>
        {% block header %}
        <header>
            <div id="container">
                <div id="logo"></div>
                <div id="title">
                    <div id="clubname">GenZ BODHI</div>
                </div>
                <div id="design">
                </div>
            </div>

        </header>
        {% endblock %}
        <!-- <div class="content-title">
            {% block contentTitle %}
            {% endblock %}                
        </div> -->
        <main>
        {% block main %}

        {% endblock %}
        </main>
        {% block navbar %}
        <nav>
            <a href="{% url 'events:eventUrl' %}" style="text-decoration: none;"><i class="fa-solid fa-bullhorn fa-xl"></i></a>
            <!-- <i class="fa-solid fa-globe fa-xl"></i> -->
            <a href="{% url 'blogs:blogUrl' %}" style="text-decoration: none;"><i class="fa-brands fa-blogger fa-2xl"></i></a>
            <a href="{% url 'feeds:home' %}" style="text-decoration: none;"><i class="fa-solid fa-house fa-xl" ></i></a>
            <i class="fa-solid fa-user-group fa-xl"></i>
            <i class="fa-solid fa-bars fa-xl menu"></i>

            <!-- Assuming a variable named 'current_page' is available in your context -->


        </nav>   
        
        <div class="sidebar-container">
            <div class="sidebar">
                <div class="propic-cont">
                    <div class="profile-picture">
                        {% if user.is_authenticated %}
                            <img src="/{{profile.profileImage}}" alt="">
                        {% else %}
                            <img src="profile/default.jpeg" alt="">
                        {% endif %}
                    </div>
                    <div class="profilename">
                        {% if user.is_authenticated %}
                            <p>{{user.username}}</p>
                        {% endif %}
                    </div>
                </div>

                {% if user.is_authenticated %}
                    <a href="{% url 'profiles:logout' %}">
                        <p class="bar_element">logout</p>
                    </a>
                {% else %}
                    <a href="{% url 'profiles:register' %}">
                        <p class="bar_element">sign up</p>
                    </a>
                    <a href="{% url 'profiles:login' %}">
                        <p class="bar_element">log in</p>
                    </a>
                {% endif %}

            
                
            </div>
        </div>
        {% endblock %}
       

        <script src="{% static 'base.js' %}" type="text/javascript" async defer></script>
        {% block extraScript %} 
        <script type="text/javascript">
        (function (d, t) {
            var v = d.createElement(t), s = d.getElementsByTagName(t)[0];
            v.onload = function () {
                window.voiceflow.chat.load({
                    verify: { projectID: '65ab3498a561e33f91ca3320' },
                    url: 'https://general-runtime.voiceflow.com',
                    versionID: 'production'
                });
            }
            v.src = "https://cdn.voiceflow.com/widget/bundle.mjs"; v.type = "text/javascript"; 
            s.parentNode.insertBefore(v, s)
        })(document, 'script');
    //     document.getElementById('chatbot').addEventListener('click', function () {
    //     window.voiceflow.chat.toggle(); // You may need to adjust this function based on the chatbot library you are using
    // });
    </script>


        {% endblock %}
    </body>
</html>

templates/blog.html
{% extends 'base.html' %} 

{% block extraStyle %} 
    <style>
        .blogOuterContainer{
            margin: 10px;
            background-color: whitesmoke;
        }
        .card{
            display: grid;
            grid-template-rows:12rem 3rem 2.5rem;
            margin-bottom: 1rem;
            background-color: white;
            border-radius: 4px;
            height: fit-content;
            box-shadow: rgba(60, 64, 67, 0.3) 0px 1px 2px 0px, rgba(60, 64, 67, 0.15) 0px 1px 3px 1px;
        }
        .imageContainer{
            height: 100%;
            width: 100%;
        }
        .imageContainer img{
            border-top-right-radius: 4px;
            border-top-left-radius: 4px;
            height: 100%;
            width: 100%;
        }
        .headingContainer{
            font-size: 1rem;
            font-weight: bolder;
            margin: 5px 10px;
        }

        .footerContainer{
            display: flex;
            justify-content: space-between;
            margin: 10px;
        }
        .nameTimeContainer{
            display: flex;
            justify-content: space-around;
            
            font-size: 0.8rem;
        }
        .nameTimeContainer span{
            margin: 0 2px;
        }
        .socialMediaContainer{
            display: flex;
            justify-content: space-around;
            width: 100px;
        }
    </style>
{% endblock %}

{% block main %} 

    <div class="blogOuterContainer">
    <!--    <div class="card">
            <div class="imageContainer">
                <img src="/post/WIN_20220506_22_06_46_Pro.jpg" alt="">
            </div>
            <div class="headingContainer">
                <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Assumenda q ....</p>
            </div>
            <div class="footerContainer">
                <div class="nameTimeContainer">
                    <p><span>Karan raj</span> <span>&middot;</span><span>2d ago</span></p>
                </div>
                <div class="socialMediaContainer">
                    <i class="fa-regular fa-heart"></i>
                    <i class="fa-solid fa-comment"></i>
                    <i class="fa-solid fa-share-nodes"></i>
                    
                </div>
            </div>
        </div> -->

        {% for blog in blogs %} 
        <div class="card"  onclick="window.location.href='/blogs/{{blog.blogSlug}}'">
            <div class="imageContainer">
                <img src="{{blog.imageContent.url}}" alt="">
            </div>
            <div class="headingContainer">
                <p>{{blog.heading | truncatewords:8}}</p>
            </div>
            <div class="footerContainer">
                <div class="nameTimeContainer">
                    <p><span>{{blog.postedBy.username}}</span> <span>&middot;</span><span>{{blog.postedOn}}</span></p>
                </div>
                <div class="socialMediaContainer">
                    <i class="fa-regular fa-heart"></i>
                    <i class="fa-solid fa-comment"></i>
                    <i class="fa-solid fa-share-nodes"></i>
                    
                </div>
            </div>
        </div>
        {% endfor %}


        <!-- <div class="card" onclick="window.location.href='/blogs/asdf'">
            <div class="imageContainer">
                <img src="/post/WIN_20220506_22_06_46_Pro.jpg" alt="">
            </div>
            <div class="headingContainer">
                <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Assumenda qui, architecto, molestiae quia doloremque ani....</p>
            </div>
            <div class="footerContainer">
                <div class="nameTimeContainer">
                    <p><span>Karan raj</span> <span>&middot;</span><span>2d ago</span></p>
                </div>
                <div class="socialMediaContainer">
                    <i class="fa-regular fa-heart"></i>
                    <i class="fa-solid fa-share-nodes"></i>
                    <i class="fa-solid fa-comment"></i>
                </div>
            </div>
        </div>
    </div> -->

    <a href="{% url 'blogs:postform' %}">
        {% include "addcontent.html" %}
    </a>

    

{% endblock %}

templates/events.html
{% extends 'base.html' %}

{% block extraLink %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
            crossorigin="anonymous"></script>
{% endblock %}
{% block main %}
    <div class="main-box d-flex flex-column align-content-center">
        
        <div class="card text-center m-3">
            <h5 class="card-header fw-bolder">
                Featured
            </h5>
            <img src="/post/WIN_20220506_22_06_46_Pro.jpg" class="card-img-top" alt="...">
            <div class="card-body">
                <h5 class="card-title">Special title treatment</h5>
                <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
                <a href="#" class="btn btn-primary">Let's Go</a>
            </div>
            <div class="card-footer text-muted">
                2 days ago
            </div>
        </div>
        <div class="btn-group btn-group-lg m-3" role="group" aria-label="...">
            <button type="button" class="btn btn-outline-secondary active" id="events">Events</button>
            <button type="button" class="btn btn-outline-secondary" id="podcasts">Podcasts</button>
        </div>
        <div class="card" style="width: 22rem; margin: .3rem auto;">
            <img src="/post/WIN_20220506_22_06_46_Pro.jpg" class="card-img-top" alt="...">
            <div class="card-body">
                <h5 class="card-title">Killing drug addicts</h5>
                <p class="card-text">Kill some of the notorious durg dealers, cartels and victims of dtug addicts for a quick buck</p>
                <div class="d-flex justify-content-between">
                    <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
                    <div href="#" class="btn btn-primary">Register</div>
                </div>
            </div>
        </div>
        <div class="card" style="width: 22rem; margin: .3rem auto;">
            <img src="/post/WIN_20220506_22_06_46_Pro.jpg" class="card-img-top" alt="...">
            <div class="card-body">
                <h5 class="card-title">Killing drug addicts</h5>
                <p class="card-text">Kill some of the notorious durg dealers, cartels and victims of dtug addicts for a quick
                    buck</p>
                <div class="d-flex justify-content-between">
                    <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
                    <div href="#" class="btn btn-primary">Register</div>
                </div>
            </div>
        </div>
    </div>
    
{% endblock %}

{% block extraScript %} 
    <script>
        let events = document.getElementById("events");
        let podcasts = document.getElementById("podcasts");

        events.addEventListener("click", ()=>{
            if (podcasts.classList.contains("active")){
                podcasts.classList.remove("active")
            }
           
            events.classList.add("active")
        })

        
        podcasts.addEventListener("click", ()=>{
            if (events.classList.contains("active")){
                events.classList.remove("active")
            }
           
            podcasts.classList.add("active")
        })

    </script>
{% endblock %}

templates/feeds.html
{% extends 'base.html' %}
{% load static %}
{% block title %}<title>feeds</title>{% endblock %}

{% block extraLink %} 
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
        crossorigin="anonymous"></script>

{% endblock %}

{% block extraStyle %}
<link rel="stylesheet" href="{% static 'feeds.css' %}">
{% endblock %}

{% block main %}

{% for post in posts %}
    {% for profile in profiles %}
        {% if profile.user == post.postedBy %}
        {% include "post.html" with textmessage=post.textContent username=post.postedBy propicsrc=profile.profileImage imagesrc=post.imageContent only%}
        {% endif %}
    {% endfor %}
{% endfor %}

<a href="{% url 'feeds:postform' %}">
    {% include "addcontent.html" %}
</a>

{% endblock %}

templates/fullBlog.html
{% extends 'base.html' %} 

{% block extraStyle %} 
    <style>
    
        .fullBlogContainer{
            margin: 10px;
        }
        .backContainer{
            margin: 10px;
            display: flex;
            gap: 0.2rem;
            align-items: center;
        }
        .headNameContainer > p{
            font-weight: bolder;
            font-size: 20px;
            text-align: center;
        }
        .nameShareContainer{
            display: flex;
            justify-content: space-between;
            margin: 10px;
        }
        .nameShareContainer > p{
            margin: 5px;
            display: flex;
            flex-direction: column;
            line-height: 0.8rem;
        }
        .socialMediaContainer{
            display: flex;
            justify-content: space-around;
            width: 100px;
            align-items: center;
        }
        .imageContainer{
            height: 100%;
            width: 100%;
        }
        .imageContainer img{
            border-radius: 4px;
            height: 100%;
            width: 100%;
        }
        .contentContainer{
            margin: 10px;
            line-height: 1rem;
            text-indent: 0.5rem;
        }
        .contentContainer p{
            margin: 10px 0;
        }
        .backUpvoteContainer{
            display: flex;
            margin: 20px;
            justify-content: space-between;
        }

    </style>
{% endblock %}

{% block main %} 
    <div class="fullBlogContainer">
        <div class="backContainer" onclick="window.location.href='/blogs/'">
            <i class="fa-solid fa-arrow-left"></i>
            <span>Back</span>
        </div>
        <div class="headNameContainer">
            <p>{{blog.heading}}</p>
            <div class="nameShareContainer">
                <p><span style="font-size: 16px; padding: 0;">{{blog.postedby.username}}</span><span style="font-size: 14px; padding: 0;">2d ago</span></p>
                <div class="socialMediaContainer">
                    <i class="fa-regular fa-heart"></i>
                    <i class="fa-solid fa-comment"></i>
                    <i class="fa-solid fa-share-nodes"></i>
                    
                </div>
            </div>
        </div>
        <div class="imageContainer">
            <img src="/{{blog.imageContent}}" alt="">
        </div>
        <div class="contentContainer">
            <p>{{blog.textContent}}</p>
        </div>
        <!-- <div class="backUpvoteContainer">
            <i class="fa-solid fa-circle-chevron-left"></i>
            <i class="fa-solid fa-circle-chevron-right"></i>
        </div> -->
    </div>


{% endblock %}

templates/login.html
{% extends 'base.html' %}
{% load static %}
{% block extraStyle %}
    <link rel="stylesheet" href="{% static 'login.css' %}">
{% endblock %}

{% block main %}
    <div class="container">
        {% for message in messages %}
            <p>{{message}}</p>
        {% endfor %}
        <form action="{% url 'profiles:login' %}" method="post">
            {% csrf_token %}
            <div class="email field">
                <label for="username">Username:</label>
                <input type="text" name="username" id="username" placeholder="Adam">
            </div>
            <div class="password field">
                <label for="Password">Password:</label>
                <input type="password" name="password" id="password1" placeholder="*******">
            </div>
            <div class="submit">
                <input type="submit" value="Login">
            </div>
        </form>
    </div>
{% endblock %}

templates/post.html
<!-- <div class="posts">
    <div class="profile">
        <div class="profile-pic">
            <img src={{propicsrc}} alt="" class="profileimg" style="display: inline;">
        </div>
        <div class="user-details">
            <p class="username" style="display: inline;">{{username}}</p>
        </div>
    </div>
    <div class="text-message">{{ textmessage }}</div>
    {% if imagesrc %}
    <div class="img-section">
        <img src={{imagesrc}} alt="" class="postimage" >
    </div>
    
    {% endif %}
    <div class="buttons-section">
        <i class="fa-solid fa-share fa-xl"></i>
        <i class="fa-regular fa-comment fa-xl"></i>
        <i class="fa-regular fa-thumbs-up fa-xl"></i>
    </div>
</div> -->




    <div class="container-fluid">
        <div class="row">
            <div class="col-md-6">
                <!--- \\\\\\\Post-->
                <div class="card m-2">
                    <div class="card-heade">
                        <div class="d-flex">
                            <div class="p-2">
                                <img class="rounded-circle" style="border-radius: 50%; width: 2rem; height: 2rem;" src="{{propicsrc}}" alt="">
                            </div>
                            <div class="p-2">
                                <div class="h5 m-0">{{username}}</div>
                            </div>
                        </div>
                    </div>
                    {% if imagesrc %}
                    <img src="{{imagesrc}}" style="border-radius: 0;" class="card-img-top">
                    {% endif %}
                    <div class="card-body">
                        <div class="text-muted h7 mb-1"> <small><i class="fa fa-clock-o"></i> Posted 40 min
                                ago...</small></div>
                        <h5 class="card-title">{{ textmessage }}</h5>
                    </div>
                    <div class="card-footer">
                        <button class="btn btn-outline-danger"><i class="fa fa-heart"></i> Like</button>
                        <button class="btn btn-outline-primary"><i class="fa fa-comment"></i> Comment</button>
                        <button class="btn btn-outline-warning"><i class="fa fa-mail-forward"></i> Share</button>
                    </div>

                </div>
                <!-- Post /////-->
            </div>

        </div>
    </div>

templates/postform.html
{% extends 'base.html' %}

{% block extraStyle %}
    <style>

        form {
            width: 100%;
            height: 100%;
        }

        input[type='submit'] {
            width: 30%;
        }

        .container {
            width: 80%;
            height: 70%;
            margin: 15% 10% 15% 10%;
            background-color: white;
            border-radius: 1rem;
            display: flex;
            flex-direction: column;
            justify-content: space-between;
            padding: 3%;
        }

        .container div {
            display: flex;
            flex-direction: column;
            margin-top: 5%;
        }

        .text {
            height: 5%;
            max-width: 70%;
            max-height: 50%;
        }
    </style>
{% endblock %}

{% block main %}
<div class="container">
        {% if user.is_authenticated %}
        {% for message in messages %}
            <p>{{message}}</p>
        {% endfor %}
        {% if request.path == '/postform' %}
        <form action="{% url 'feeds:postform' %}" method="post" enctype="multipart/form-data">
        {% elif request.path == '/blogs/postform' %}
        <form action="{% url 'blogs:postform' %}" method="post" enctype="multipart/form-data">

        {% endif %}

            {% csrf_token %}
            {{form.as_div}}
            <div class="field">
                <input type="submit" value="Post">
            </div>
        </form>
        {% else %}
            <h3>Login to Post your thoughts..</h3><br>
            <a href="{% url 'profiles:login' %}">login</a>
        {% endif %}
    </div>
{% endblock %}

templates/register.html
{% extends 'base.html' %}
{% load static %}
{% block extraStyle %}
    <link rel="stylesheet" href="{% static 'register.css' %}">
{% endblock %}

{% block main %}
    <div class="container">
        {% for message in messages %}
            <p>{{message}}</p>
        {% endfor %}
        <form action="register" method="post">
            {% csrf_token %}
            <div class="username field">
                <label for="username">Username:</label>
                <input type="text" name="username" id="username" placeholder="Adam">
            </div>
            <div class="email field">
                <label for="email">E-mail:</label>
                <input type="email" name="email" id="email" placeholder="Adam@email.com">
            </div>
            <div class="password field">
                <label for="Password1">Password:</label>
                <input type="password" name="password" id="password1" placeholder="*******">
            </div>
            <div class="password field">
                <label for="Password2">Repeat Password:</label>
                <input type="password" name="password2" id="password2" placeholder="*******">
            </div>
            <div class="submit">
                <input type="submit" value="Sign up">
            </div>
        </form>
    </div>
{% endblock %}